[".mozilla/firefox/arkenfox.default/chrome/includes"]
type = "archive"
url = "https://github.com/cascadefox/cascade/archive/main.tar.gz"
exact = true
stripComponents = 3
refreshPeriod = "168h"
include = ["*/chrome/includes/**", "*/integrations/gruvbox/**"]
