[Unit]
After=graphical-session.target

[Service]
ExecStop=/usr/bin/emacsclient --eval "(kill-emacs)"
ExecReload=/usr/bin/emacsclient --eval "(doom/reload)"
Slice=app-graphical.slice

[Install]
WantedBy=graphical-session.target
