[Unit]
After=graphical-session.target

[Service]
ExecStartPost=%h/.config/sh/open_org_agenda_silent.sh
ExecStop=/usr/bin/emacsclient --eval "(kill-emacs)"
ExecReload=/usr/bin/emacsclient --eval "(doom/reload)"
Slice=app-graphical.slice
TimeoutStartSec=60

[Install]
WantedBy=graphical-session.target
