[Unit]
After=graphical-session.target

[Service]
Type=simple
Environment=DISPLAY=:0
ExecStop=/usr/bin/emacsclient --eval "(kill-emacs)"
Slice=app-graphical.slice
KillMode=process

[Install]
WantedBy=graphical-session.target
