#!/usr/bin/env bash

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# fish as interactive shell
if [[ $(ps --no-header --pid=$PPID --format=comm) != "fish" && -z ${BASH_EXECUTION_STRING} && ${SHLVL} == 1 ]]; then
    shopt -q login_shell && LOGIN_OPTION='--login' || LOGIN_OPTION=''
    exec fish $LOGIN_OPTION
fi

# ble.sh
# [[ $- == *i* ]] && source /usr/share/blesh/ble.sh --noattach

# ----------------------------Prompt--------------------------- #

eval "$(oh-my-posh init bash --config="$XDG_CONFIG_HOME/oh-my-posh/themes/bubblesline.omp.toml")"

# ------------------Completions & Initializations-------------- #

if [[ -r /usr/share/bash-completion/bash_completion ]]; then
    . /usr/share/bash-completion/bash_completion
fi

eval "$(zoxide init bash)"
eval "$(fzf --bash)"
eval "$(atuin init bash)"
eval "$(direnv hook bash)"

# ---------------------------Options--------------------------- #

export LS_COLORS="$(vivid generate gruvbox-dark)"

# History
export HISTSIZE=50000
export SAVEHIST=10000
export HISTCONTROL=ignoredups:erasedups
export HISTFILE="$XDG_STATE_HOME/bash/history"
shopt -s histappend # Append to history, don't overwrite it

# Vi mode
set -o vi

# ----------------------------Binds---------------------------- #

bind '"\C-s": "sysz\n"'
bind -m vi-command '"\C-s": "i sysz\n"'

# ---------------------------Imports--------------------------- #
[ -f "$XDG_CONFIG_HOME/bash/functions" ] && . "$XDG_CONFIG_HOME/bash/functions"
[ -f "$XDG_CONFIG_HOME/bash/aliases" ] && . "$XDG_CONFIG_HOME/bash/aliases"
[ -f "$XDG_CONFIG_HOME/sh/aliases" ] && . "$XDG_CONFIG_HOME/sh/aliases"

# [[ ${BLE_VERSION-} ]] && ble-attach
