#!/usr/bin/env bash

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# fish as interactive shell
if [[ $(ps --no-header --pid="$PPID" --format=comm) != "fish" && -z ${BASH_EXECUTION_STRING} && ${SHLVL} == 1 ]]; then
    shopt -q login_shell && LOGIN_OPTION='--login' || LOGIN_OPTION=''
    # shellcheck disable=SC2086
    exec fish $LOGIN_OPTION
fi

# ----------------------------Prompt--------------------------- #

eval "$(oh-my-posh init bash --config="$XDG_CONFIG_HOME/oh-my-posh/themes/bubblesline.omp.toml")"

# ------------------Completions & Initializations-------------- #

[ -r /usr/share/bash-completion/bash_completion ] &&
    . /usr/share/bash-completion/bash_completion

eval "$(zoxide init bash)"
eval "$(atuin init bash)"
# eval "$(fzf --bash)"
eval "$(tv init bash)"
eval "$(direnv hook bash)"

# ---------------------------Options--------------------------- #

# shellcheck disable=SC2155
[ "$(command -v vivid)" != "" ] &&
    export LS_COLORS="$(vivid generate gruvbox-dark)"

# History
export HISTSIZE=50000
export SAVEHIST=10000
export HISTCONTROL=ignoredups:erasedups
export HISTFILE="$XDG_STATE_HOME/bash/history"
shopt -s histappend # Append to history, don't overwrite it

# Vi mode
set -o vi

# ----------------------------Binds---------------------------- #

# ---------------------------Imports--------------------------- #
[ -f "$XDG_CONFIG_HOME/bash/functions.sh" ] && . "$XDG_CONFIG_HOME/bash/functions.sh"
[ -f "$XDG_CONFIG_HOME/bash/aliases.sh" ] && . "$XDG_CONFIG_HOME/bash/aliases.sh"
[ -f "$XDG_CONFIG_HOME/sh/aliases.sh" ] && . "$XDG_CONFIG_HOME/sh/aliases.sh"
