#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 4

# =============================================================================
# Left prompt (Main prompt)
# =============================================================================

[[blocks]]
type = "prompt"
alignment = "left"

# --- Vi mode -----------------------------------------------------------------
[[blocks.segments]]
type = "text"
style = "diamond"
leading_diamond = ""
trailing_diamond = " "
background = "#3C3836"
foreground = "red"
template = '''
{{- if .Env.FISH__BIND_MODE -}}
  {{- if eq .Env.FISH__BIND_MODE "default" -}}
    N
  {{- else if eq .Env.FISH__BIND_MODE "insert" -}}
    I
  {{- else if eq .Env.FISH__BIND_MODE "replace_one" -}}
    R
  {{- else if eq .Env.FISH__BIND_MODE "replace" -}}
    R
  {{- else if eq .Env.FISH__BIND_MODE "visual" -}}
    V
  {{- else -}}
    ?
  {{- end -}}
{{- else if .Env.POSH_VI_MODE -}}
  {{ .Env.POSH_VI_MODE }}
{{- end -}}
'''
foreground_templates = [
  # fish
  '{{if eq .Env.FISH__BIND_MODE "default"}}blue{{end}}',
  '{{if eq .Env.FISH__BIND_MODE "insert"}}magenta{{end}}',
  '{{if eq .Env.FISH__BIND_MODE "replace_one"}}yellow{{end}}',
  '{{if eq .Env.FISH__BIND_MODE "replace"}}red{{end}}',
  '{{if eq .Env.FISH__BIND_MODE "visual"}}cyan{{end}}',
  # zsh
  '{{if contains "N" .Env.POSH_VI_MODE}}blue{{end}}',
  '{{if contains "I" .Env.POSH_VI_MODE}}magenta{{end}}',
  '{{if contains "V-L" .Env.POSH_VI_MODE}}cyan{{end}}',
  '{{if contains "V" .Env.POSH_VI_MODE}}cyan{{end}}',
  '{{if contains "R" .Env.POSH_VI_MODE}}yellow{{end}}',
]

# --- Exit code ---------------------------------------------------------------
[[blocks.segments]]
type = "status"
style = "diamond"
leading_diamond = ""
trailing_diamond = " "
foreground = "red"
background = "#3C3836"
template = "{{ if .Error }} {{ .Code }}{{ end }}"

# --- User --------------------------------------------------------------------
[[blocks.segments]]
type = "session"
style = "diamond"
leading_diamond = ""
trailing_diamond = " "
foreground = "green"
background = "#3C3836"
template = "{{ .UserName }}"

# =============================================================================
# Right prompt (Context information)
# =============================================================================

[[blocks]]
type = "rprompt"
alignment = "right"

# --- Directory ---------------------------------------------------------------
[[blocks.segments]]
type = "path"
style = "diamond"
leading_diamond = ""
trailing_diamond = ""
foreground = "#B8BB26"
background = "#3C3836"
template = " {{ .Path }}"

[blocks.segments.properties]
style = "folder"

# --- Git ---------------------------------------------------------------------
[[blocks.segments]]
type = "git"
style = "diamond"
leading_diamond = " "
trailing_diamond = ""
foreground = "lightBlue"
background = "#3C3836"
template = '''
{{- .UpstreamIcon -}}
{{- .HEAD -}}
{{- if .BranchStatus }} {{ .BranchStatus }}{{ end -}}
'''

[blocks.segments.properties]
branch_icon = " "
branch_identical_icon = ""
branch_gone_icon = ""
fetch_status = true
fetch_upstream_icon = true
source = "cli"

[blocks.segments.properties.mapped_branches]
"feat/*" = " "
"bug/*" = " "

# --- Lua ---------------------------------------------------------------------
[[blocks.segments]]
type = "lua"
style = "diamond"
leading_diamond = " "
trailing_diamond = ""
foreground = "blue"
background = "#3C3836"
template = '''
 {{ if not .Error -}}
  {{ .Full }}
{{- else -}}
  {{ .Error }}
{{- end -}}
'''

# --- Python ------------------------------------------------------------------
[[blocks.segments]]
type = "python"
style = "diamond"
leading_diamond = " "
trailing_diamond = ""
foreground = "blue"
background = "#3C3836"
template = '''
 {{ if not .Error -}}
  {{ .Full }}
  {{- if .Venv }} ({{ .Venv }}){{ end }}
{{- else -}}
  {{ .Error }}
{{- end -}}
'''

# --- Go -----------------------------------------------------------------------
[[blocks.segments]]
type = "go"
style = "diamond"
leading_diamond = " "
trailing_diamond = ""
foreground = "lightBlue"
background = "#3C3836"
template = '''
󰟓 {{ if not .Error -}}
  {{ .Full }}
{{- else -}}
  {{ .Error }}
{{- end -}}
'''

# --- Java --------------------------------------------------------------------
[[blocks.segments]]
type = "java"
style = "diamond"
leading_diamond = " "
trailing_diamond = ""
foreground = "#F29111"
background = "#3C3836"
template = '''
 {{ if not .Error -}}
  {{ .Full }}
{{- else -}}
  {{ .Error }}
{{- end -}}
'''

# --- Kotlin ------------------------------------------------------------------
[[blocks.segments]]
type = "kotlin"
style = "diamond"
leading_diamond = " "
trailing_diamond = ""
foreground = "#906cff"
background = "#3C3836"
template = '''
 {{ if not .Error -}}
  {{ .Full }}
{{- else -}}
  {{ .Error }}
{{- end -}}
'''

[blocks.segments.properties]
fetch_version = false
