#!/usr/bin/env bash

actions=('add' 'open' 'edit' 'del' 'random' 'dmenu')

buku_cmd="buku --nostdin --tacit --np --nc"
# buku_cmd="buku --nostdin --tacit --np --nc --db $XDG_DATA_HOME/gosuki/gosuki.db"

url_regexp='^(http(s)?:\/\/)?(www.)?([a-zA-Z0-9])+([\-\.]{1}[a-zA-Z0-9]+)*\.[a-zA-Z]{2,5}(:[0-9]{1,5})?(\/[^\s]*)?$'

declare -A flags=(
    ["add"]="--add"
    ["open"]="--open"
    ["edit"]="--update"
    ["del"]="--delete"
    ["random"]="--random -p -f 3"
    ["dmenu"]="-p -f 3"
)

debug=false
args_without_debug=()
for arg in "$@"; do
    if [[ "$arg" == "--debug" ]]; then
        debug=true
    else
        args_without_debug+=("$arg")
    fi
done
set -- "${args_without_debug[@]}"

log() {
    local level="$1"
    local msg="$2"
    if [[ "$debug" == true ]]; then
        if [[ -n "$QUTE_FIFO" ]]; then
            echo "message-$level '$msg'" >>"$QUTE_FIFO"
        else
            echo "message-$level '$msg'" >&2
        fi
    fi
    if [[ "$level" == "error" ]]; then
        exit 1
    fi
}

run_buku() {
    local action="$1"
    shift
    local -a flags_array=(${flags[$action]})
    $buku_cmd "${flags_array[@]}" "$@"
    local ret=$?
    if [[ $ret -eq 0 ]]; then
        log info "Success"
    else
        log error "Something wrong happened"
    fi
    return $ret
}

search() {
    open_count="$1"
    search_flag="$2"
    query="${3//\*/\\*}"

    result_str=$($buku_cmd --format 1 "$search_flag" "$query" | grep -Eo '^[0-9]+' | head -n "$open_count")

    echo "${result_str//\\n/ }"
}

parse_query() {
    local query=""
    while [[ "$1" =~ [^-][[:alpha:]]* ]]; do
        query+="$1 "
        shift
    done
    echo "${query%" "}"
}

open_selected_ids() {
    cut -d ' ' -f 1 | xargs --no-run-if-empty buku -o
}

action="add"

for a in "${actions[@]}"; do
    if [[ "$a" == "$1" ]]; then
        action="$1"
        shift
        break
    fi
done

while :; do
    case "$1" in
    -n*)
        if [[ "$1" =~ -n[[:digit:]]+ ]]; then
            limit=$(echo "$1" | grep -Eo '[[:digit:]]+')
            shift
        elif [[ "$1" == "-n" ]] && [[ "$2" =~ [[:digit:]]+ ]]; then
            limit="$2"
            shift 2
        else
            log error "The -n flag only accepts a number"
        fi
        ;;
    -s)
        search=true
        search_type="--sany"
        search_query=$(parse_query "$@")
        shift "$#"
        ;;
    -S)
        search=true
        search_type="--sall"
        search_query=$(parse_query "$@")
        shift "$#"
        ;;
    *)
        break
        ;;
    esac
done

case $action in
add)
    if echo "$1" | grep -qP "$url_regexp"; then
        run_buku add "$@"
    else
        run_buku add "$QUTE_URL" "$@"
    fi
    exit $?
    ;;
open)
    if [[ -z "$1" ]] && [[ ! $search ]]; then
        log error "At least 1 argument required: index | query | tag"
    fi

    if [[ -n "$1" ]]; then
        if [[ "$1" =~ ^[[:digit:]]+$ ]] || [[ "$1" =~ ^[[:digit:]]+-[[:digit:]]+$ ]]; then
            index="$1"
        else
            search=true
            search_type="--sany"
            search_query=$(parse_query "$@")
            shift "$#"
        fi
        shift
    fi

    if [[ ! $search ]]; then
        log info "OK"
        run_buku open "$index"
    fi

    result=$(search "${limit:-1}" "$search_type" "$search_query")
    run_buku open "${result[@]}"
    exit $?
    ;;
edit)
    if [[ -z "$1" ]]; then
        log error "argument required: tag"
    fi

    run_buku edit "$@"
    exit $?
    ;;
del)
    if [[ -z "$1" ]]; then
        log error "argument required: tag | tag range"
    fi

    run_buku del "$@"
    exit $?
    ;;
random)
    run_buku random | open_selected_ids
    exit $?
    ;;
dmenu)
    if ! command -v fuzzel &>/dev/null; then
        log error "Fuzzel not found!"
    fi
    run_buku dmenu |
        fuzzel \
            -d \
            -p ' ' \
            -w 100 \
            -l 15 \
            --minimal-lines \
            --counter \
            --match-mode fuzzy \
            --with-nth 2 |
        open_selected_ids
    exit $?
    ;;
esac
