# Layer
layerrule = noanim, hyprpicker
layerrule = noanim, selection

# Windows
# windowrule = group set, class:org.pwmt.zathura
# windowrule = group deny, class:^(foot.*|nvim)$

windowrule = float, title:.*flt.*
windowrule = float, class:zenity

windowrule = tile, class:Timeshift-gtk

# Steam
windowrule = float, class:steam, title:^(Friends List|Steam Settings)$

# War Thunder
windowrule = fullscreen, class:^(Loading...)$
windowrule = stayfocused, class:^(War Thunder.*)$

windowrule = center 1, class:^(firefox)$, title:^(Save.*)$
windowrule = center 1, class:^(firefox)$, title:(^$)
windowrule = center 1, class:nm-connection-editor, title:(^ $)
windowrule = center 1, class:zenity
windowrule = center 1, class:gcr-prompter
windowrule = center 1, class:polkit-gnome-authentication-agent-1
windowrule = center 1, class:Timeshift-gtk
windowrule = center 1, class:org.qbittorrent.qBittorrent

windowrule = size 50% 50%, class:^(firefox)$, title:^(Save.*)$
windowrule = size 50% 50%, class:^(firefox)$, title:(^$)
windowrule = size 50% 50%, class:zenity
windowrule = size 50% 50%, class:org.qbittorrent.qBittorrent
windowrule = size 50% 50%, title:.*yazi.*

windowrule = suppressevent maximize, class:.*

# Workspaces
windowrule = workspace 6 silent, class:^(net.lutris.Lutris|steam)$

windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
windowrule = bordersize 0, floating:0, onworkspace:f[1]
