# Layer
layerrule = noanim, hyprpicker
layerrule = noanim, selection

# Windows
windowrule = group set,  class:org.pwmt.zathura
windowrule = group deny, class:^(foot.*|nvim)$

windowrule = float, title:.*flt.*
windowrule = float, class:galculator
windowrule = float, class:qt-sudo
windowrule = float, class:zenity

windowrule = tile, class:Timeshift-gtk
windowrule = tile, class:sioyek

windowrule = center 1, class:^(firefox|zen-alpha|LibreWolf)$, title:^(Save.*)$
windowrule = center 1, class:^(firefox|zen-alpha|LibreWolf)$, title:(^$)
windowrule = center 1, class:zenity
windowrule = center 1, class:nemo,                            title:(^$)
windowrule = center 1, class:gcr-prompter
windowrule = center 1, class:nm-connection-editor,            title:(^ $)
windowrule = center 1, class:polkit-gnome-authentication-agent-1
windowrule = center 1, class:Timeshift-gtk
windowrule = center 1, class:org.qbittorrent.qBittorrent

windowrule = size 50% 50%, class:^(firefox|zen-alpha|LibreWolf)$, title:^(Save.*)$
windowrule = size 50% 50%, class:^(firefox|zen-alpha|LibreWolf)$, title:(^$)
windowrule = size 50% 50%, class:zenity
windowrule = size 50% 50%, class:org.qbittorrent.qBittorrent
windowrule = size 50% 50%, title:.*mp.*
windowrule = size 50% 50%, title:.*yazi.*
windowrule = size 25% 55%, class:galculator

windowrule = suppressevent maximize, class:.*

# Workspaces
windowrule = workspace 6 silent, class:^(net.lutris.Lutris|steam|Waydroid)$

windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
windowrule = bordersize 0, floating:0, onworkspace:f[1]
