#######################
#     LAYER RULES     #
#######################

layerrule {
  name = color-picker
  match:class = hyprpicker

  no_anim = 1
}

layerrule {
  name = screenshot-selection
  match:class = selection

  no_anim = 1
}

########################
#     WINDOW RULES     #
########################

windowrule {
  name = personal-float
  match:title = .*flt.*

  float = 1
}

windowrule {
  name = personal-yazi-size
  match:title = .*yazi.*

  size = 50% 50%
}

windowrule {
  name = suppress-maximize
  match:title = .*

  suppress_event = maximize
}

# Steam
windowrule {
  name = steam-float
  match:class = steam
  match:title = ^(Friends List|Список друзей|Steam Settings|Настройки|Добавить стороннюю игру|Настройки раздела|Сведения о системе|Системный отчёт|Среда выполнения Steam — сведения о системе)$

  float = 1
}

windowrule {
  name = steam-center
  match:class = steam
  match:title = ^(Friends List|Список друзей|Steam Settings|Настройки|Добавить стороннюю игру|Настройки раздела|Сведения о системе|Системный отчёт|Среда выполнения Steam — сведения о системе)$

  center = 1
}

windowrule {
  name = steam-size
  match:class = steam
  match:title = ^(Friends List|Список друзей|Steam Settings|Настройки|Добавить стороннюю игру|Настройки раздела|Сведения о системе|Системный отчёт|Среда выполнения Steam — сведения о системе)$

  size = 50% 50%
}

# Timeshift
windowrule {
  name = timeshift-tile
  match:class = Timeshift-gtk

  tile = 1
}

windowrule {
  name = timeshift-center
  match:class = Timeshift-gtk

  center = 1
}

# Firefox
windowrule {
  name = firefox-center
  match:class = ^(firefox)$
  match:title = ^(Save.*)$

  center = 1
}

windowrule {
  name = firefox-size
  match:class = ^(firefox)$
  match:title = ^(Save.*)$

  size = 50% 50%
}

windowrule {
  name = firefox-center
  match:class = ^(firefox)$
  match:title = (^$)

  center = 1
}

windowrule {
  name = firefox-size
  match:class = ^(firefox)$
  match:title = (^$)

  size = 50% 50%
}

# Zenity
windowrule {
  name = zenity-float
  match:class = zenity

  float = 1
}

windowrule {
  name = zenity-size
  match:class = zenity

  size = 50% 50%
}

# Network Manager
windowrule {
  name = nm-center
  match:class = nm-connection-editor
  match:title = (^ $)

  center = 1
}


windowrule {
  name = nm-center
  match:class = nm-connection-editor
  match:title = (^ $)

  center = 1
}

# qBittorrent
windowrule {
    name = qbittorrent-center
    match:class = org.qbittorrent.qBittorrent

    center = 1
}

windowrule {
    name = qbittorrent-center
    match:class = org.qbittorrent.qBittorrent

    size = 50% 50%
}

# Gnome
windowrule {
    name = gcr-prompter-center
    match:class = gcr-prompter

    center = 1
}

windowrule {
    name = polkit-gnome-center
    match:class = polkit-gnome-authentication-agent-1

    center = 1
}

# War Thunder
windowrule {
    name = warthunder-fullscreen
    match:class = ^(Loading...)$

    fullscreen = 1
}

windowrule {
    name = warthunder-stayfocused
    match:class = ^(War Thunder.*)$

    stay_focused = 1
}

# INFO: Tabbed alternative. Bullshit.
# windowrule = group set, class:org.pwmt.zathura
# windowrule = group deny, class:^(foot.*|nvim)$

###########################
#     WORKSPACE RULES     #
###########################

windowrule {
    name = game-workspace
    match:class = ^(net.lutris.Lutris|steam)$

    workspace = 6 silent
}

windowrule {
    name = smart-gaps
    match:workspace = w[tv1]

    border_size = 0
    float = 0
}

windowrule {
    name = smart-gaps
    match:workspace = f[1]

    border_size = 0
    float = 0
}
