#:schema https://yazi-rs.github.io/schemas/keymap.json

[mgr]
prepend_keymap = [
  { on = "q", run = "plugin confirm-quit", desc = "Quit the process" },
  # Hopping
  { on = "J", run = "plugin parent-arrow 1", desc = "Next parent directory" },
  { on = "K", run = "plugin parent-arrow -1", desc = "Previous parent directory" },
  # Seeking
  { on = "<C-f>", run = "seek 5" },
  { on = "<C-b>", run = "seek -5" },
  # Operation
  { on = "l", run = "plugin smart-enter" },
  { on = "!", run = 'shell "$SHELL" --block', desc = "Open shell here" },
  { on = "y", run = [
    'shell -- for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list',
    "yank",
  ] },
  { on = ["p", "p"], run = "paste", desc = "Paste yanked files" },
  { on = ["p", "c"], run = "plugin save-clipboard-to-file", desc = "Paste clipboard content to file" },
  { on = "t", run = "plugin smart-tab", desc = "Create a tab and enter the hovered directory" },
  # Goto
  { on = ["g", "h"], run = "cd ~", desc = "Home" },
  { on = ["g", "c"], run = "cd ~/.config", desc = "~/.config" },
  { on = ["g", "C"], run = "cd ~/.local/share/chezmoi/dot_config", desc = "~/.dot_config" },
  { on = ["g", "d"], run = "cd ~/Downloads", desc = "~/Downloads" },
  { on = ["g", "D"], run = "cd ~/Documents", desc = "~/Documents" },
  { on = ["g", "m"], run = "cd ~/Music", desc = "~/Music" },
  { on = ["g", "M"], run = "cd /mnt", desc = "Drives" },
  { on = ["g", "v"], run = "cd ~/Videos", desc = "~/Videos" },
  { on = ["g", "p"], run = "cd ~/Pictures", desc = "~/Pictures" },
  { on = ["g", "P"], run = "cd ~/Projects", desc = "~/Projects" },
  { on = ["g", "t"], run = "plugin recycle-bin -- open", desc = "Trash" },
  { on = ["g", "."], run = "hidden toggle", desc = "Toggle hidden" },
  { on = ["g", "?"], run = "help", desc = "Open help" },
  # Zoxide
  { on = ["z", "z"], run = "plugin zoxide", desc = "Zoxide" },
  { on = ["z", "a"], run = "shell -- zoxide add .", desc = "Add to zoxide" },
  { on = ["z", "r"], run = "shell -- zoxide remove .", desc = "Remove from zoxide" },
  { on = "Z", run = "plugin fzf" },
  # Chezmoi
  { on = ["C", "a"], run = "shell -- chezmoi add %s", desc = "Add to chezmoi" },
  { on = ["C", "A"], run = "shell -- chezmoi add --encrypt %s", desc = "Add to chezmoi (encrypted)" },
  { on = ["C", "r"], run = "shell -- chezmoi re-add %s", desc = "Re-add to chezmoi" },
  { on = ["C", "R"], run = "shell -- chezmoi re-add --encrypt %s", desc = "Re-add to chezmoi (encrypted)" },
  { on = ["C", "e"], run = "shell -- chezmoi edit %s", desc = "Edit in chezmoi" },
  # Mount
  { on = "M", run = "plugin mount", desc = "Mount manager" },
  # Chmod
  { on = ["c", "m"], run = "plugin chmod", desc = "Chmod on selected files" },
  # Diff
  { on = [".", "d"], run = "plugin diff", desc = "Diff the selected with the hovered file" },
  # Compress
  { on = ["c", "a", "a"], run = "plugin compress", desc = "Archive selected files" },
  { on = ["c", "a", "p"], run = "plugin compress -p", desc = "Archive selected files (password)" },
  { on = ["c", "a", "P"], run = "plugin compress -ph", desc = "Archive selected files (password+header)" },
  # What-size
  { on = [".", "s"], run = "plugin what-size", desc = "Show the size of the selected files or cwd" },
  # Preview
  { on = "T", run = "plugin toggle-pane max-preview", desc = "Toggle maximaze preview" },
  # Zoom
  { on = "=", run = "plugin zoom 1", desc = "Zoom in hovered file" },
  { on = "-", run = "plugin zoom -1", desc = "Zoom out hovered file" },
  # Smart filter
  { on = "F", run = "plugin smart-filter", desc = "Smart filter" },
  # Easyjump
  { on = "i", run = "plugin easyjump", desc = "Easyjump" },
  # Git
  { on = ["\\", "g", "r"], run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"', desc = "Go to the root (git)" },
  { on = ["\\", "g", "v"], run = "plugin vcs-files", desc = "Show Git file changes" },
  # Trash
  { on = "u", run = "plugin restore", desc = "Restore last deleted files/folders" },
  { on = "R", run = "plugin recycle-bin", desc = "Open recycle bin menu" },
  # Thumbnail
  { on = ["g", "V"], run = "plugin thumbnail", desc = "Open current directory in gallery" },
]
