#:schema https://yazi-rs.github.io/schemas/yazi.json

# ===========================================================================
# Preview
# ===========================================================================

[preview]
max_width = 900
max_height = 1200
image_quality = 90
image_delay = 0
# FIX: Need test
# ueberzug_offset = [5, 1.2, 0, 0]

# ===========================================================================
# Opener definitions & rules
# ===========================================================================

[opener]
image = [
  { for = "linux", run = 'swayimg "$@"', orphan = true, block = true },
]
pdf = [
  { for = "linux", run = 'zathura "$@"', orphan = true, block = true },
]

[open]
prepend_rules = [
  { mime = "image/{vnd.djvu,x-djvu,djvu}", use = ["open", "reveal"] },
  { mime = "image/*", use = ["image", "open", "reveal"] },
  # { mime = "application/pdf", use = ["pdf", "open"] },
]

# ===========================================================================
# Other settings
# ===========================================================================

[tasks]
image_bound = [10000, 10000]

[input]
cursor_blink = true

# ===========================================================================
# Plugins
# ===========================================================================

# ---------------------------------------------------------------------------
# git.yazi
# ---------------------------------------------------------------------------

[[plugin.prepend_fetchers]]
url = "*"
run = "git"
group = "git"

[[plugin.prepend_fetchers]]
url = "*/"
run = "git"
group = "git"

# ---------------------------------------------------------------------------
# office.yazi
# ---------------------------------------------------------------------------

[[plugin.prepend_preloaders]]
mime = "application/openxmlformats-officedocument.*"
run = "office"

[[plugin.prepend_preloaders]]
mime = "application/oasis.opendocument.*"
run = "office"

[[plugin.prepend_preloaders]]
mime = "application/ms-*"
run = "office"

[[plugin.prepend_preloaders]]
mime = "application/msword"
run = "office"

[[plugin.prepend_preloaders]]
url = "*.docx"
run = "office"

[[plugin.prepend_previewers]]
mime = "application/openxmlformats-officedocument.*"
run = "office"

[[plugin.prepend_previewers]]
mime = "application/oasis.opendocument.*"
run = "office"

[[plugin.prepend_previewers]]
mime = "application/ms-*"
run = "office"

[[plugin.prepend_previewers]]
mime = "application/msword"
run = "office"

[[plugin.prepend_previewers]]
url = "*.docx"
run = "office"

# ---------------------------------------------------------------------------
# djvu-view.yazi
# ---------------------------------------------------------------------------

[[plugin.prepend_previewers]]
mime = "image/{vnd.djvu,x-djvu,djvu}"
run = "djvu-view"

# ---------------------------------------------------------------------------
# epub-preview.yazi
# ---------------------------------------------------------------------------

[[plugin.prepend_previewers]]
mime = "application/epub+zip"
run = "epub-preview"

# ---------------------------------------------------------------------------
# exifaudio.yazi
# ---------------------------------------------------------------------------

[[plugin.prepend_previewers]]
mime = "audio/*"
run = "exifaudio"
