#:schema https://yazi-rs.github.io/schemas/yazi.json

[preview]
max_width = 900
max_height = 1200
image_quality = 90
image_delay = 0
# FIX: Need test
# ueberzug_offset = [5, 1.2, 0, 0]

[opener]
image = [
  { for = "linux", run = 'swayimg "$@"', orphan = true, block = true },
]
pdf = [
  { for = "linux", run = 'zathura "$@"', orphan = true, block = true },
]

[open]
prepend_rules = [
  { mime = "image/{vnd.djvu,x-djvu,djvu}", use = ["open", "reveal"] },
  { mime = "image/*", use = ["image", "open", "reveal"] },
  # { mime = "application/pdf", use = ["pdf", "open"] },
]

[tasks]
image_bound = [10000, 10000]

[plugin]
prepend_previewers = [
  { mime = "audio/*", run = "exifaudio" },
  { mime = "application/epub+zip", run = "epub-preview" },
  { mime = "image/{vnd.djvu,x-djvu,djvu}", run = "djvu-view" },
]
prepend_fetchers = [
  { id = "git", name = "*", run = "git" },
  { id = "git", name = "*/", run = "git" },
]

[input]
cursor_blink = true
