theme = "gruvbox"

[editor]
cursorline = true
line-number = "relative"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true

[keys.normal]
C-s = ":write"
Z = { Q = ":quit!", Z = ":write-quit!" }
C-y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
  ":set mouse false",
  ":set mouse true",
]
C-g = [
  ":write-all",
  ":new",
  ":insert-output lazygit",
  ":set mouse false",
  ":set mouse true",
  ":buffer-close!",
  ":redraw",
  ":reload-all",
]

[keys.normal.space]
q = { q = ":quit-all" }

[keys.normal."C-backspace"]
r = ":config-reload"
o = ":o ~/.local/share/chezmoi/dot_config/helix/config.toml"
l = ":o ~/.local/share/chezmoi/dot_config/helix/languages.toml"
