theme = "gruvbox"

[editor]
cursorline = true
line-number = "relative"
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-progress-messages = true
display-inlay-hints = true

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[keys.normal]
H = ":bp"
L = ":bn"
Z = { Q = ":q!", Z = ":wq!" }
C-s = ":w"
C-y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
  ":set mouse false",
  ":set mouse true",
]
C-g = [
  ":wa",
  ":n",
  ":insert-output lazygit",
  ":set mouse false",
  ":set mouse true",
  ":buffer-close!",
  ":redraw",
  ":rla",
]

[keys.normal.space]
q = { q = ":qa" }
b = { b = "buffer_picker", d = ":bc", D = ":bc!", o = ":bco", n = ":n" }
"," = "buffer_picker"
"." = ":n"
u = { h = ":toggle lsp.display-inlay-hints", L = ":toggle line-number 'absolute' 'relative'", f = ":toggle auto-format", p = ":toggle auto-pairs" }

[keys.normal."C-backspace"]
r = ":config-reload"
o = ":o ~/.local/share/chezmoi/dot_config/helix/config.toml"
l = ":o ~/.local/share/chezmoi/dot_config/helix/languages.toml"
