theme = "gruvbox"

[editor]
cursorline = true
line-number = "relative"
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-progress-messages = true
display-inlay-hints = true

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[keys.normal]
H = ":bp"
L = ":bn"
Z = { Q = ":q!", Z = ":wq!" }
C-s = ":w"
C-y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
  ":set mouse false",
  ":set mouse true",
]
C-g = [
  ":wa",
  ":n",
  ":insert-output lazygit",
  ":set mouse false",
  ":set mouse true",
  ":buffer-close!",
  ":redraw",
  ":rla",
]

[keys.normal.space]
"," = "buffer_picker"
"." = ":n"
q.q = ":qa"
b.b = "buffer_picker"
b.d = ":bc"
b.D = ":bc!"
b.o = ":bco"
b.n = ":n"
u.h = ":toggle lsp.display-inlay-hints"
u.L = ":toggle line-number 'absolute' 'relative'"
u.f = ":toggle auto-format"
u.p = ":toggle auto-pairs"

[keys.normal."C-d"]
r = ":config-reload"
d = [":cd ~/.local/share/chezmoi", "file_picker"]
c = [":cd ~/.local/share/chezmoi", ":o dot_config/helix/config.toml"]
l = [":cd ~/.local/share/chezmoi", ":o dot_config/helix/languages.toml"]
