#:schema https://yazi-rs.github.io/schemas/keymap.json

[mgr]
prepend_keymap = [
  # Unbind defaults
  { on = ["t", "t"], run = "noop" },
  { on = ["t", "r"], run = "noop" },
  { on = "y", run = "noop" },
  { on = "p", run = "noop" },
  { on = "z", run = "noop" },
  { on = ".", run = "noop" },
  # QoL
  { on = "l", run = "plugin smart-enter", desc = "Enter the child directory or open in editor" },
  { on = "q", run = "plugin confirm-quit", desc = "Quit the process" },
  # Motions
  ## Zoxide
  { on = ["z", "z"], run = "plugin zoxide", desc = "Zoxide" },
  { on = ["z", "a"], run = "shell -- zoxide add .", desc = "Add to zoxide" },
  { on = ["z", "r"], run = "shell -- zoxide remove .", desc = "Remove from zoxide" },
  ## fzf
  { on = "Z", run = "plugin fzf", desc = "Jump to a file/directory via fzf" },
  ## Easyjump
  { on = "i", run = "plugin easyjump", desc = "Easyjump" },
  ## Hopping
  { on = "J", run = "plugin parent-arrow 1", desc = "Next parent directory" },
  { on = "K", run = "plugin parent-arrow -1", desc = "Previous parent directory" },
  # Operations
  ## Yank
  { on = ["y", "y"], run = ['shell -- for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list', "yank"], desc = "Yank selected files (copy)" },
  { on = ["y", "c"], run = "shell -- wl-copy < \"$@\"", desc = "Yank file content (copy)" },
  ## Paste
  { on = ["p", "p"], run = "paste", desc = "Paste yanked files" },
  { on = ["p", "c"], run = "plugin save-clipboard-to-file", desc = "Paste clipboard content to file" },
  ## Filter
  { on = "F", run = "plugin smart-filter", desc = "Smart filter" },
  # Tabs
  { on = ["T", "t"], run = "plugin smart-tab", desc = "Create a tab and enter the hovered directory" },
  { on = ["T", "r"], run = "tab_rename --interactive", desc = "Rename current tab" },
  { on = ["T", "c"], run = "close", desc = "Close the current tab, or quit if it's last" },
  # Goto
  { on = ["g", "h"], run = "cd ~", desc = "Home" },
  { on = ["g", "c"], run = "cd ~/.config", desc = "~/.config" },
  { on = ["g", "C"], run = "cd ~/.local/share/chezmoi/dot_config", desc = "~/.dot_config" },
  { on = ["g", "d"], run = "cd ~/Downloads", desc = "~/Downloads" },
  { on = ["g", "D"], run = "cd ~/Documents", desc = "~/Documents" },
  { on = ["g", "m"], run = "cd ~/Music", desc = "~/Music" },
  { on = ["g", "M"], run = "cd /mnt", desc = "Drives" },
  { on = ["g", "v"], run = "cd ~/Videos", desc = "~/Videos" },
  { on = ["g", "p"], run = "cd ~/Pictures", desc = "~/Pictures" },
  { on = ["g", "P"], run = "cd ~/Projects", desc = "~/Projects" },
  { on = ["g", "t"], run = "plugin recycle-bin -- open", desc = "Trash" },
  # Action
  { on = "!", run = 'shell "$SHELL" --block', desc = "Open shell here" },
  { on = ["t", "h"], run = "hidden toggle", desc = "Toggle hidden" },
  { on = ["g", "."], run = "hidden toggle", desc = "Toggle hidden" },
  { on = ["g", "?"], run = "help", desc = "Open help" },
  # Operations with files
  ## Chmod
  { on = ["c", "m"], run = "plugin chmod", desc = "Chmod on selected files" },
  # Diff
  { on = [".", "d"], run = "plugin diff", desc = "Diff the selected with the hovered file" },
  ## Compress
  { on = ["c", "a", "a"], run = "plugin compress", desc = "Archive selected files" },
  { on = ["c", "a", "p"], run = "plugin compress -p", desc = "Archive selected files (password)" },
  { on = ["c", "a", "P"], run = "plugin compress -ph", desc = "Archive selected files (password+header)" },
  ## What-size
  { on = [".", "s"], run = "plugin what-size", desc = "Show the size of the selected files or cwd" },
  # Preview
  { on = ["t", "p"], run = "plugin toggle-pane max-preview", desc = "Toggle maximize preview" },
  { on = ["t", "m"], run = "plugin mediainfo -- toggle-metadata", desc = "Toggle media preview metadata" },
  ## Seeking
  { on = "<C-f>", run = "seek 5", desc = "Scroll preview down" },
  { on = "<C-b>", run = "seek -5", desc = "Scroll preview up" },
  ## Zoom
  { on = "=", run = "plugin zoom 1", desc = "Zoom in hovered file" },
  { on = "-", run = "plugin zoom -1", desc = "Zoom out hovered file" },
  ## Show thumbnails using swayimg
  { on = ["g", "V"], run = "plugin thumbnail", desc = "Show thumbnails for current directory" },
  # Utilities
  ## Desktop Trash Can
  { on = "u", run = "plugin restore", desc = "Restore last deleted files/folders" },
  { on = "R", run = "plugin recycle-bin", desc = "Open recycle bin menu" },
  ## Git
  { on = ["\\", "g", "r"], run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"', desc = "Go to the root (git)" },
  { on = ["\\", "g", "v"], run = "plugin vcs-files", desc = "Show Git file changes" },
  ## Chezmoi
  { on = ["C", "a"], run = "shell -- chezmoi add %s", desc = "Add to chezmoi" },
  { on = ["C", "A"], run = "shell -- chezmoi add --encrypt %s", desc = "Add to chezmoi (encrypted)" },
  { on = ["C", "r"], run = "shell -- chezmoi re-add %s", desc = "Re-add to chezmoi" },
  { on = ["C", "R"], run = "shell -- chezmoi re-add --encrypt %s", desc = "Re-add to chezmoi (encrypted)" },
  { on = ["C", "e"], run = "shell -- chezmoi edit %s", desc = "Edit in chezmoi" },
  ## Mount manager
  { on = "M", run = "plugin mount", desc = "Mount manager" },
]
