[metadata]
name = "dotfiles"
description = "A channel to select from your user's dotfiles"
requirements = ["fd", "bat", "chezmoi"]

[source]
command = "fd -t f . $XDG_DATA_HOME/chezmoi/"

[preview]
command = "bat -n --color=always '{}'"
