[metadata]
name = "git-reflog"
description = "A channel to select from git reflog entries"
requirements = ["git", "bash"]

[source]
command = "bash -c 'git reflog'"
output = "{split: :0}"

[preview]
command = "bash -c 'git show -p --stat --pretty=fuller --color=always \"{0}\"'"
