#NoColor
#NoVersion
#NoAUR
#NoFlatpak
NoNotification
#NewsNum=5
#NewsTimeout=10
AURHelper=yay
PrivilegeElevationCommand=doas
#KeepOldPackages=3
#KeepUninstalledPackages=0
#DiffProg=$DIFFPROG
TrayIconStyle=light
