XDG_CACHE_HOME=${XDG_CACHE_HOME:-$HOME/.cache}
XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}
XDG_STATE_HOME=${XDG_STATE_HOME:-$HOME/.local/state}
XDG_PICTURES_DIR=${XDG_PICTURES_DIR:-$HOME/Pictures}
XDG_SCREENSHOTS_DIR=$XDG_PICTURES_DIR/screenshots
XDG_WALLPAPERS_DIR=$XDG_PICTURES_DIR/wallpapers

BUN_HOME=$XDG_DATA_HOME/bun
CARGO_HOME=$XDG_DATA_HOME/cargo
RUSTUP_HOME=$XDG_DATA_HOME/rustup
GOPATH=$XDG_DATA_HOME/go
WINEPREFIX=$XDG_DATA_HOME/wine
PYTHONSTARTUP=$XDG_CONFIG_HOME/python/pythonrc
_JAVA_OPTIONS=-Djava.util.prefs.userRoot=$XDG_CONFIG_HOME/java
NUGET_PACKAGES=$XDG_CACHE_HOME/NuGetPackages
DOTNET_CLI_HOME=$XDG_DATA_HOME/dotnet
RENPY_PATH_TO_SAVES=$XDG_DATA_HOME/renpy
CUPS_CONFIG_DIR=$XDG_CONFIG_HOME/cups
CUPS_CACHE_DIR=$XDG_CACHE_HOME/cups
CUPS_DATA_DIR=$XDG_DATA_HOME/cups
RLWRAP_HOME=$XDG_DATA_HOME/rlwrap
NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc
GNUPGHOME=$XDG_DATA_HOME/gnupg
SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/ssh-agent.socket
PASSWORD_STORE_DIR=$XDG_DATA_HOME/gopass/stores/root
SCREENRC=$XDG_CONFIG_HOME/screen/screenrc
EMACSDIR=$XDG_CONFIG_HOME/emacs

PATH=$BUN_HOME/bin:$GOPATH/bin:$CARGO_HOME/bin:$XDG_CONFIG_HOME/emacs/bin:$HOME/.local/bin:$PATH
