export GPG_TTY="$(tty)"

export VISUAL=nvim
export EDITOR="$VISUAL"

export TERMINAL=footclient
export TERM="$TERMINAL"
export TERMCMD="$TERMINAL --title='foot-yazi-flt'"

export BROWSER=qutebrowser

export DIFFPROG='nvim -d'
export MANPAGER='nvim +Man!'

export PAGER=less
export LESS='-i -M -F'

export BAT_THEME=gruvbox-dark

export DOTNET_CLI_TELEMETRY_OPTOUT="1"
export POWERSHELL_TELEMETRY_OPTOUT="1"

export DMENU="fuzzel -d"

export SUDO_ASKPASS="$HOME/.local/bin/askpass"
export DOAS_ASKPASS="$SUDO_ASKPASS"

export VDPAU_DRIVER=radeonsi
export LIBVA_DRIVER_NAME=radeonsi

[ -f "$XDG_CONFIG_HOME/bash/fzf_config.sh" ] && . "$XDG_CONFIG_HOME/bash/fzf_config.sh"
