VISUAL=nvim
EDITOR=$VISUAL
TERMINAL=footclient
TERM=$TERMINAL
TERMCMD=$TERMINAL --title=footclient-center-half-float-yazi
BROWSER=qutebrowser
GRIMBLAST_EDITOR=satty --filename
DIFFPROG=nvim -d
MANPAGER='nvim +Man!'
PAGER=less
LESS='-i -M -F'
BAT_THEME=gruvbox-dark
DOTNET_CLI_TELEMETRY_OPTOUT=1
POWERSHELL_TELEMETRY_OPTOUT=1
DMENU=fuzzel -d --minimal-lines
SUDO_ASKPASS=$HOME/.local/bin/askpass
DOAS_ASKPASS=$SUDO_ASKPASS
VDPAU_DRIVER=radeonsi
LIBVA_DRIVER_NAME=radeonsi
