-- ============================================================================
-- General settings
-- ============================================================================
swayimg.set_mode("viewer")
swayimg.set_window_size(1280, 720)
swayimg.enable_overlay(false)
swayimg.enable_decoration(false)
swayimg.set_dnd_button("Shift-MouseRight")

-- Signal handlers (SIGUSR1/SIGUSR2)
swayimg.viewer.on_signal("USR1", function()
	swayimg.viewer.reload()
end)
swayimg.viewer.on_signal("USR2", function()
	swayimg.viewer.switch_image("next")
end)

-- ============================================================================
-- Image list
-- ============================================================================
swayimg.imagelist.set_order("alpha")
swayimg.imagelist.enable_reverse(false)
swayimg.imagelist.enable_recursive(false)
swayimg.imagelist.enable_adjacent(true)
swayimg.imagelist.enable_fsmon(true)

-- ============================================================================
-- Font & text layer (global)
-- ============================================================================
swayimg.text.set_font("monospace")
swayimg.text.set_size(12)
swayimg.text.set_foreground(0xffebdbb2)
swayimg.text.set_shadow(0xd0000000)
swayimg.text.set_background(0x00000000)
swayimg.text.set_padding(10)
swayimg.text.set_timeout(5)
swayimg.text.set_status_timeout(3)
swayimg.text.hide()

-- ============================================================================
-- Viewer mode
-- ============================================================================
-- Background & transparency
swayimg.viewer.set_window_background(0xff282828)
swayimg.viewer.set_image_chessboard(10, 0xffaaaaaa, 0xff555555)

-- Scale, position, antialiasing
local antialiasing_enabled = true

-- Force set scale mode on window resize (useful for tiling compositors)
swayimg.on_window_resize(function()
	local mode = swayimg.get_mode()
	if mode == "viewer" then
		swayimg.viewer.set_fix_scale("optimal")
	elseif mode == "slideshow" then
		swayimg.slideshow.set_fix_scale("optimal")
	end
end)
swayimg.viewer.set_default_position("center")
swayimg.enable_antialiasing(antialiasing_enabled)
swayimg.viewer.enable_loop(true)
swayimg.viewer.limit_history(50)
swayimg.viewer.limit_preload(25)

-- Text overlay
swayimg.viewer.set_text("topleft", {
	"{name}",
	"{format}",
	"{sizehr}",
	"{frame.width}x{frame.height}",
	"{meta.*}",
})
swayimg.viewer.set_text("topright", {
	"{list.index}/{list.total}",
})
swayimg.viewer.set_text("bottomleft", {
	"{scale}%",
	"{frame.index}/{frame.total}",
})

-- ============================================================================
-- Slideshow mode
-- ============================================================================
swayimg.slideshow.set_timeout(5)
swayimg.slideshow.set_window_background(0xff282828)
swayimg.slideshow.set_image_chessboard(10, 0xffaaaaaa, 0xff555555)
swayimg.slideshow.set_default_scale("optimal")
swayimg.slideshow.set_default_position("center")
swayimg.slideshow.enable_loop(true)
swayimg.slideshow.enable_centering(true)
swayimg.slideshow.limit_preload(25)
swayimg.slideshow.limit_history(50)

-- Text overlay
swayimg.slideshow.set_text("bottomright", {
	"{dir}",
	"Status: {status}",
})

-- ============================================================================
-- Gallery mode
-- ============================================================================
swayimg.gallery.set_thumb_size(200)
swayimg.gallery.set_selected_scale(1.15)
swayimg.gallery.set_aspect("fill")
swayimg.gallery.set_padding_size(5)
swayimg.gallery.set_selected_color(0xff3c3836)
swayimg.gallery.set_unselected_color(0xff32302f)
swayimg.gallery.set_border_color(0xff928374)
swayimg.gallery.set_border_size(4)
swayimg.gallery.set_window_color(0xff282828)
swayimg.gallery.limit_cache(100)
swayimg.gallery.enable_preload(true)
swayimg.gallery.enable_pstore(false)

-- Text overlay
swayimg.gallery.set_text("bottomright", {
	"{name}",
	"Status: {status}",
})

-- ============================================================================
-- Key bindings – helper functions
-- ============================================================================
local function step_left(dx)
	local pos = swayimg.viewer.get_position()
	swayimg.viewer.set_abs_position(pos.x + dx, pos.y)
end
local function step_right(dx)
	local pos = swayimg.viewer.get_position()
	swayimg.viewer.set_abs_position(pos.x - dx, pos.y)
end
local function step_up(dy)
	local pos = swayimg.viewer.get_position()
	swayimg.viewer.set_abs_position(pos.x, pos.y + dy)
end
local function step_down(dy)
	local pos = swayimg.viewer.get_position()
	swayimg.viewer.set_abs_position(pos.x, pos.y - dy)
end
local function zoom(amount)
	local scale = swayimg.viewer.get_scale()
	swayimg.viewer.set_abs_scale(scale + amount)
end

-- ============================================================================
-- Viewer mode key bindings
-- ============================================================================
local viewer = swayimg.viewer

-- Navigation
viewer.on_key("Home", function()
	viewer.switch_image("first")
end)
viewer.on_key("End", function()
	viewer.switch_image("last")
end)
viewer.on_key("g", function()
	viewer.switch_image("first")
end)
viewer.on_key("Shift+g", function()
	viewer.switch_image("last")
end)
viewer.on_key("Prior", function()
	viewer.switch_image("prev")
end)
viewer.on_key("Next", function()
	viewer.switch_image("next")
end)
viewer.on_key("h", function()
	viewer.switch_image("prev")
end)
viewer.on_key("j", function()
	viewer.switch_image("next")
end)
viewer.on_key("k", function()
	viewer.switch_image("prev")
end)
viewer.on_key("l", function()
	viewer.switch_image("next")
end)
viewer.on_key("Shift+Space", function()
	viewer.switch_image("prev")
end)
viewer.on_key("Space", function()
	viewer.switch_image("next")
end)
viewer.on_key("Shift+r", function()
	viewer.switch_image("random")
end)
viewer.on_key("Shift+d", function()
	viewer.switch_image("prev_dir")
end)
viewer.on_key("d", function()
	viewer.switch_image("next_dir")
end)
viewer.on_key("Shift+o", function()
	viewer.prev_frame()
end)
viewer.on_key("o", function()
	viewer.next_frame()
end)

-- Special actions
viewer.on_key("s", function()
	swayimg.set_mode("slideshow")
end)
viewer.on_key("n", function()
	viewer.animation_stop()
end)
viewer.on_key("f", function()
	swayimg.toggle_fullscreen()
end)
viewer.on_key("Return", function()
	swayimg.set_mode("gallery")
end)

-- Movement & zoom
viewer.on_key("Left", function()
	step_left(10)
end)
viewer.on_key("Right", function()
	step_right(10)
end)
viewer.on_key("Up", function()
	step_up(10)
end)
viewer.on_key("Down", function()
	step_down(10)
end)
viewer.on_key("Equal", function()
	zoom(0.1)
end)
viewer.on_key("Plus", function()
	zoom(0.1)
end)
viewer.on_key("Minus", function()
	zoom(-0.1)
end)
viewer.on_key("w", function()
	viewer.set_fix_scale("width")
end)
viewer.on_key("Shift+w", function()
	viewer.set_fix_scale("height")
end)
viewer.on_key("z", function()
	viewer.set_fix_scale("fit")
end)
viewer.on_key("Shift+z", function()
	viewer.set_fix_scale("fill")
end)
viewer.on_key("0", function()
	viewer.set_fix_scale("real")
end)
viewer.on_key("BackSpace", function()
	viewer.set_fix_scale("optimal")
end)
viewer.on_key("Alt+z", function()
	viewer.set_fix_scale("keep")
end)
viewer.on_key("Alt+s", function()
	viewer.set_fix_scale("optimal")
end)
viewer.on_key("Alt+p", function()
	viewer.set_fix_position("center")
end)

-- Transformations
viewer.on_key("bracketleft", function()
	viewer.rotate(90)
end)
viewer.on_key("bracketright", function()
	viewer.rotate(270)
end)
viewer.on_key("m", function()
	viewer.flip_vertical()
end)
viewer.on_key("Shift+m", function()
	viewer.flip_horizontal()
end)

-- Misc
viewer.on_key("a", function()
	antialiasing_enabled = not antialiasing_enabled
	swayimg.enable_antialiasing(antialiasing_enabled)
end)
viewer.on_key("r", function()
	viewer.reload()
end)
viewer.on_key("Delete", function()
	local img = viewer.get_image()
	if img then
		os.execute('trash-put "' .. img.path .. '"')
		viewer.switch_image("next")
	end
end)
viewer.on_key("Shift+Delete", function()
	local img = viewer.get_image()
	if img then
		os.execute('rm -f "' .. img.path .. '"')
		viewer.switch_image("next")
	end
end)
viewer.on_key("q", function()
	swayimg.exit()
end)

-- Mouse bindings
viewer.on_mouse("ScrollLeft", function()
	step_right(5)
end)
viewer.on_mouse("ScrollRight", function()
	step_left(5)
end)
viewer.on_mouse("ScrollUp", function()
	viewer.switch_image("prev")
end)
viewer.on_mouse("ScrollDown", function()
	viewer.switch_image("next")
end)
viewer.on_mouse("Ctrl+ScrollUp", function()
	zoom(0.1)
end)
viewer.on_mouse("Ctrl+ScrollDown", function()
	zoom(-0.1)
end)
viewer.on_mouse("Shift+ScrollUp", function()
	step_up(5)
end)
viewer.on_mouse("Shift+ScrollDown", function()
	step_down(5)
end)
viewer.on_mouse("Shift+ScrollLeft", function()
	step_left(5)
end)
viewer.on_mouse("Shift+ScrollRight", function()
	step_right(5)
end)
viewer.on_mouse("Alt+ScrollUp", function()
	viewer.prev_frame()
end)
viewer.on_mouse("Alt+ScrollDown", function()
	viewer.next_frame()
end)
viewer.on_mouse("MouseLeft", function()
	viewer.set_drag_button("MouseLeft")
end)
viewer.on_mouse("MouseSide", function()
	viewer.switch_image("prev")
end)
viewer.on_mouse("MouseExtra", function()
	viewer.switch_image("next")
end)
viewer.on_mouse("MouseRight", function()
	swayimg.set_mode("gallery")
end)

-- ============================================================================
-- Slideshow mode key bindings
-- ============================================================================
local slideshow = swayimg.slideshow

slideshow.on_key("Home", function()
	slideshow.switch_image("first")
end)
slideshow.on_key("End", function()
	slideshow.switch_image("last")
end)
slideshow.on_key("g", function()
	slideshow.switch_image("first")
end)
slideshow.on_key("Shift+g", function()
	slideshow.switch_image("last")
end)
slideshow.on_key("Prior", function()
	slideshow.switch_image("prev")
end)
slideshow.on_key("Next", function()
	slideshow.switch_image("next")
end)
slideshow.on_key("Left", function()
	slideshow.switch_image("prev")
end)
slideshow.on_key("Right", function()
	slideshow.switch_image("next")
end)
slideshow.on_key("Up", function()
	slideshow.switch_image("prev")
end)
slideshow.on_key("Down", function()
	slideshow.switch_image("next")
end)
slideshow.on_key("h", function()
	slideshow.switch_image("prev")
end)
slideshow.on_key("j", function()
	slideshow.switch_image("next")
end)
slideshow.on_key("k", function()
	slideshow.switch_image("prev")
end)
slideshow.on_key("l", function()
	slideshow.switch_image("next")
end)
slideshow.on_key("Shift+r", function()
	slideshow.switch_image("random")
end)
slideshow.on_key("Shift+d", function()
	slideshow.switch_image("prev_dir")
end)
slideshow.on_key("d", function()
	slideshow.switch_image("next_dir")
end)
slideshow.on_key("Space", function()
	slideshow.set_timeout(0) -- pause (timeout 0 stops timer)
end)
slideshow.on_key("f", function()
	swayimg.toggle_fullscreen()
end)
slideshow.on_key("Delete", function()
	local img = slideshow.get_image()
	if img then
		os.execute('trash-put "' .. img.path .. '"')
		slideshow.switch_image("next")
	end
end)
slideshow.on_key("Shift+Delete", function()
	local img = slideshow.get_image()
	if img then
		os.execute('rm -f "' .. img.path .. '"')
		slideshow.switch_image("next")
	end
end)
slideshow.on_key("Return", function()
	swayimg.set_mode("viewer")
end)
slideshow.on_key("q", function()
	swayimg.exit()
end)
slideshow.on_mouse("MouseRight", function()
	swayimg.set_mode("gallery")
end)

-- ============================================================================
-- Gallery mode key bindings
-- ============================================================================
local gallery = swayimg.gallery

gallery.on_key("Home", function()
	gallery.switch_image("first")
end)
gallery.on_key("End", function()
	gallery.switch_image("last")
end)
gallery.on_key("g", function()
	gallery.switch_image("first")
end)
gallery.on_key("Shift+g", function()
	gallery.switch_image("last")
end)
gallery.on_key("Left", function()
	gallery.switch_image("left")
end)
gallery.on_key("Right", function()
	gallery.switch_image("right")
end)
gallery.on_key("Up", function()
	gallery.switch_image("up")
end)
gallery.on_key("Down", function()
	gallery.switch_image("down")
end)
gallery.on_key("h", function()
	gallery.switch_image("left")
end)
gallery.on_key("j", function()
	gallery.switch_image("down")
end)
gallery.on_key("k", function()
	gallery.switch_image("up")
end)
gallery.on_key("l", function()
	gallery.switch_image("right")
end)
gallery.on_key("Prior", function()
	gallery.switch_image("pgup")
end)
gallery.on_key("Next", function()
	gallery.switch_image("pgdown")
end)
gallery.on_key("s", function()
	swayimg.set_mode("slideshow")
end)
gallery.on_key("f", function()
	swayimg.toggle_fullscreen()
end)
gallery.on_key("Return", function()
	swayimg.set_mode("viewer")
end)
gallery.on_key("a", function()
	antialiasing_enabled = not antialiasing_enabled
	swayimg.enable_antialiasing(antialiasing_enabled)
end)
gallery.on_key("r", function()
	gallery.reload()
end)
gallery.on_key("Equal", function()
	gallery.set_thumb_size(gallery.get_thumb_size() + 20)
end)
gallery.on_key("Plus", function()
	gallery.set_thumb_size(gallery.get_thumb_size() + 20)
end)
gallery.on_key("Minus", function()
	gallery.set_thumb_size(gallery.get_thumb_size() - 20)
end)
gallery.on_key("Delete", function()
	local img = gallery.get_image()
	if img then
		os.execute('trash-put "' .. img.path .. '"')
		gallery.switch_image("next")
	end
end)
gallery.on_key("Shift+Delete", function()
	local img = gallery.get_image()
	if img then
		os.execute('rm -f "' .. img.path .. '"')
		gallery.switch_image("next")
	end
end)
gallery.on_key("q", function()
	swayimg.exit()
end)

-- Mouse bindings for gallery
gallery.on_mouse("ScrollLeft", function()
	gallery.switch_image("left")
end)
gallery.on_mouse("ScrollRight", function()
	gallery.switch_image("right")
end)
gallery.on_mouse("ScrollUp", function()
	gallery.switch_image("up")
end)
gallery.on_mouse("ScrollDown", function()
	gallery.switch_image("down")
end)
gallery.on_mouse("Ctrl+ScrollUp", function()
	gallery.set_thumb_size(gallery.get_thumb_size() + 20)
end)
gallery.on_mouse("Ctrl+ScrollDown", function()
	gallery.set_thumb_size(gallery.get_thumb_size() - 20)
end)
