# vim:fileencoding=utf-8:foldmethod=marker
# : Manager {{{

[manager]
cwd = { fg = "#81A1C1" }  # Blue

# Hovered
hovered = { bg = "#3F4551" }  # Darkened background
preview_hovered = { underline = true }

# Find
find_keyword = { fg = "#BF616A", italic = true, underline = true }  # Red
find_position = { fg = "#EBCB8B", italic = true }  # Orange

# Marker
marker_copied = { fg = "#E5E9F0", bg = "#A3BE8C" }  # Light gray on Green
marker_cut = { fg = "#E5E9F0", bg = "#BF616A" }  # Light gray on Red
marker_marked = { fg = "#E5E9F0", bg = "#88C0D0" }  # Light gray on Cyan
marker_selected = { fg = "#E5E9F0", bg = "#EBCB8B" }  # Light gray on Orange

# Tab
tab_active = { bg = "#3F4551", fg = "#81A1C1" }  # Darkened background, Blue text
tab_inactive = {}
tab_width = 1

# Count
count_copied = { fg = "#A3BE8C", bg = "#3F4551" }  # Green on Darkened background
count_cut = { fg = "#BF616A", bg = "#3F4551" }  # Red on Darkened background
count_selected = { fg = "#A3BE8C", bg = "#3F4551" }  # Green on Darkened background

# Border
border_symbol = "│"
border_style = { fg = "#3F4551" }  # Darkened background

# : }}}
# : Status {{{

[status]
separator_open = " "
separator_close = " "
separator_style = { fg = "#81A1C1", bg = "#3F4551" }  # Blue on Darkened background

# Mode
mode_normal = { fg = "#3F4551", bg = "#81A1C1", bold = true }  # Dark gray on Blue
mode_select = { fg = "#3F4551", bg = "#9AAFE6", bold = true }  # Dark gray on Blue
mode_unset = { fg = "#3F4551", bg = "#9AAFE6", bold = true }  # Dark gray on Blue

# Progress
 
progress_label = { fg = "#3F4551", bold = true }  # Light gray
progress_normal = { fg = "#A3BE8C", bg = "#3F4551" }  # Green on Darkened background
progress_error = { fg = "#BF616A", bg = "#3F4551" }  # Red on Darkened background

# Permissions
permissions_t = { fg = "#A3BE8C" }  # Green
permissions_r = { fg = "#BF616A" }  # Red
permissions_w = { fg = "#EBCB8B" }  # Orange
permissions_x = { fg = "#A3BE8C" }  # Green
permissions_s = { fg = "#E5E9F0" }  # Light gray

# : }}}
# : Select {{{

[select]
border = { fg = "#A3BE8C" }  # Green
active = { fg = "#EBCB8B", bold = true }  # Orange
inactive = {}

# : }}}
# : Input {{{

[input]
border = { fg = "#A3BE8C" }  # Green
title = {}
value = {}
selected = { reversed = true }

# : }}}
# : Completion {{{

[completion]
border = { fg = "#A3BE8C" }  # Green

# : }}}
# : Tasks {{{

[tasks]
border = { fg = "#A3BE8C" }  # Green
title = {}
hovered = { fg = "#EBCB8B", underline = true }  # Orange

# : }}}
# : Which {{{

[which]
mask = { bg = "#3F4551" }  # Darkened background
cand = { fg = "#A3BE8C" }  # Green
rest = { fg = "#E5E9F0" }  # Light gray
desc = { fg = "#EBCB8B" }  # Orange
separator = "  "
separator_style = { fg = "#E5E9F0" }  # Light gray

# : }}}
# : Help {{{

[help]
on = { fg = "#A3BE8C" }  # Green
run = { fg = "#EBCB8B" }  # Orange
hovered = { reversed = true, bold = true }
footer = { fg = "#E5E9F0", bg = "#3F4551" }  # Light gray on Black

# : }}}
# : Notify {{{

[notify]
title_info = { fg = "#A3BE8C" }  # Green
title_warn = { fg = "#BF616A" }  # Red
title_error = { fg = "#EBCB8B" }  # Orange

# : }}}
# : File-specific styles {{{

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#EBCB8B" },  # Orange

    # Media
    { mime = "video/*", fg = "#BF616A" },  # Red
    { mime = "audio/*", fg = "#BF616A" },  # Red

    # Archives
    { mime = "application/zip", fg = "#B48EAD" },  # Magenta
    { mime = "application/x-tar", fg = "#B48EAD" },  # Magenta
    { mime = "application/x-bzip*", fg = "#B48EAD" },  # Magenta
    { mime = "application/x-bzip2", fg = "#B48EAD" },  # Magenta
    { mime = "application/x-7z-compressed", fg = "#B48EAD" },  # Magenta
    { mime = "application/x-rar", fg = "#B48EAD" },  # Magenta
    { mime = "application/x-xz", fg = "#B48EAD" },  # Magenta

    # Documents
    { mime = "application/doc", fg = "#A3BE8C" },  # Green
    { mime = "application/pdf", fg = "#A3BE8C" },  # Green
    { mime = "application/rtf", fg = "#A3BE8C" },  # Green
    { mime = "application/vnd.*", fg = "#A3BE8C" },  # Green

    # Fallback
    { name = "*", fg = "#E5E9F0" },  # Blue
    { name = "*/", fg = "#81A1C1" }  # Blue
]

# : }}}
