#!/bin/sh

# Pretty PATH
alias path='echo "$PATH" | tr ":" " "'
alias path_list='echo "$PATH" | tr ":" "\n" | sort'

# eza
alias lr='ls -R'

# yazi
alias y='yazi'

# Clipboard
alias clipboard_history="cliphist list | fzf -d $'\t' --with-nth 2 | cliphist decode | wl-copy"

# bottom
alias btmb='btm -b --hide_avg_cpu --theme gruvbox'

# Web
alias news="newsboat"
alias duck="BROWSER=links ddgr"

# IP addresses
alias myip="dig +short myip.opendns.com @resolver1.opendns.com"
alias ips="ifconfig -a | grep -o 'inet6\? \(addr:\)\?\s\?\(\(\([0-9]\+\.\)\{3\}[0-9]\+\)\|[a-fA-F0-9:]\+\)' | awk '{ sub(/inet6? (addr:)? ?/, \"\"); print }'"

# Speedtest
alias speedtest="speedtest-go"

# Reload the shell (i.e. invoke as a login shell)
alias reload='exec "$SHELL" -l'

# Clean bc
alias bc='bc -q'

# buku
alias b='buku --suggest'

##############
# Translator #
##############

alias t='trans :ru'
alias tl='trans :ru --shell --brief'
alias tt='trans :en'
alias ttl='trans :en --shell --brief'

##########
# Neovim #
##########

alias v="nvim"
alias vz="nvim -c 'Telescope zoxide list'"
alias vd="nvim -c 'Telescope chezmoi find_files'"

###########
# Chezmoi #
###########

alias cz='chezmoi'
alias cza='chezmoi add'
alias czcd='chezmoi cd'
alias cze='chezmoi edit'
alias czea='chezmoi edit --apply'
alias czra='chezmoi re-add'

###########
# Ansible #
###########

alias a='ansible '
alias aconf='ansible-config '
alias acon='ansible-console '
alias aver='ansible-version'
alias arinit='ansible-role-init'
alias aplaybook='ansible-playbook '
alias ainv='ansible-inventory '
alias adoc='ansible-doc '
alias agal='ansible-galaxy '
alias apull='ansible-pull '
alias aval='ansible-vault'

##########
# Docker #
##########

alias dbl='docker build'
alias dcin='docker container inspect'
alias dcls='docker container ls'
alias dclsa='docker container ls -a'
alias dib='docker image build'
alias dii='docker image inspect'
alias dils='docker image ls'
alias dipu='docker image push'
alias dipru='docker image prune -a'
alias dirm='docker image rm'
alias dit='docker image tag'
alias dlo='docker container logs'
alias dnc='docker network create'
alias dncn='docker network connect'
alias dndcn='docker network disconnect'
alias dni='docker network inspect'
alias dnls='docker network ls'
alias dnrm='docker network rm'
alias dpo='docker container port'
alias dps='docker ps'
alias dpsa='docker ps -a'
alias dpu='docker pull'
alias dr='docker container run'
alias drit='docker container run -it'
alias drm='docker container rm'
alias 'drm!'='docker container rm -f'
alias dst='docker container start'
alias drs='docker container restart'
alias dsta='docker stop $(docker ps -q)'
alias dstp='docker container stop'
alias dtop='docker top'
alias dvi='docker volume inspect'
alias dvls='docker volume ls'
alias dvprune='docker volume prune'
alias dxc='docker container exec'
alias dxcit='docker container exec -it'

##########
# Golang #
##########

alias gob='go build'
alias goc='go clean'
alias god='go doc'
alias goe='go env'
alias gof='go fmt'
alias gofa='go fmt ./...'
alias gofu='gofumpt'
alias gofua='gofumpt ./...'
alias gofx='go fix'
alias gog='go get'
alias goga='go get ./...'
alias goi='go install'
alias gol='go list'
alias gom='go mod'
alias gomt='go mod tidy'
alias gopa='cd $GOPATH'
alias gopb='cd $GOPATH/bin'
alias gops='cd $GOPATH/src'
alias gor='go run'
alias got='go test'
alias gota='go test ./...'
alias goto='go tool'
alias gotoc='go tool compile'
alias gotod='go tool dist'
alias gotofx='go tool fix'
alias gov='go vet'
alias gove='go version'
alias gow='go work'

###########
# systemd #
###########

# --now commands
alias sc-enable-now="sc-enable --now"
alias sc-disable-now="sc-disable --now"
alias sc-mask-now="sc-mask --now"

alias scu-enable-now="scu-enable --now"
alias scu-disable-now="scu-disable --now"
alias scu-mask-now="scu-mask --now"

# --failed commands
alias scu-failed='systemctl --user --failed'
alias sc-failed='systemctl --failed'

##########
# Pacman #
##########
# Additional info:
# - https://wiki.archlinux.org/index.php/Pacman_Tips

alias pacupg='doas pacman -Syu'
alias pacin='doas pacman -S'
alias paclean='doas pacman -Sc'
alias pacins='doas pacman -U'
alias paclr='doas pacman -Scc'
alias pacre='doas pacman -R'
alias pacrem='doas pacman -Rns'
alias pacrep='pacman -Si'
alias pacreps='pacman -Ss'
alias pacloc='pacman -Qi'
alias paclocs='pacman -Qs'
alias pacinsd='doas pacman -S --asdeps'
alias pacmir='doas pacman -Syy'
alias paclsorphans='doas pacman -Qdt'
alias pacrmorphans='doas pacman -Rs $(pacman -Qtdq)'
alias pacfileupg='doas pacman -Fy'
alias pacfiles='pacman -F'
alias pacls='pacman -Ql'
alias pacown='pacman -Qo'
alias pacupd="doas pacman -Sy"
alias pacmanallkeys='doas pacman-key --refresh-keys'

if command -v yay >/dev/null 2>&1; then
    alias yaconf='yay -Pg'
    alias yaclean='yay -Sc'
    alias yaclr='yay -Scc'
    alias yaupg='yay -Syu'
    alias yasu='yay -Syu --noconfirm'
    alias yain='yay -S'
    alias yains='yay -U'
    alias yare='yay -R'
    alias yarem='yay -Rns'
    alias yarep='yay -Si'
    alias yareps='yay -Ss'
    alias yaloc='yay -Qi'
    alias yalocs='yay -Qs'
    alias yalst='yay -Qe'
    alias yaorph='yay -Qtd'
    alias yainsd='yay -S --asdeps'
    alias yamir='yay -Syy'
    alias yaupd="yay -Sy"
fi
